language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-7.4
- export CXX="g++-7.4"

script:
  - gcc ./Delegate/TestDelegate.cpp -std=c++11 -o TestDelegate
#  - ./TestDelegate
