sudo: false
dist: trusty
language: cpp
os:
  - linux
compiler:
  - gcc
install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [[ $CXX = g++ ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5 # not sure why we needed this
  packages:
    - gcc-4.9
    - g++-4.9

script:
  - gcc ./Delegate/TestDelegate.cpp -std=c++11 -o TestDelegate
#  - ./TestDelegate
