# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_ubuntu_manually:
    docker:
      - image: ubuntu:24.04
    # https://circleci.com/developer/machine/image/ubuntu-2204
    # machine:
    #   image: ubuntu-2204:2024.05.1
    # resource_class: arm.large
    
    environment:
      NUM_THERADS: 3

    steps:
      - checkout

      # - run:
      #     name: Update Latest GCC
      #     command: |
      #       apt-get update
      #       DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt install -y software-properties-common
      #       add-apt-repository ppa:ubuntu-toolchain-r/test
      #       apt update
      #       apt install gcc-14 g++-14
      #       update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10
      #       update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10
      #       update-alternatives --config gcc
      #       update-alternatives --config g++
      #       gcc --version
      #       g++ --version

      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                build-essential \
                git \
                curl \
                zip \
                cmake \

      - run:
          name: Install vcpkg & libs
          command: |
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.sh
            ./vcpkg install boost-filesystem
            ./vcpkg integrate install
      
      - run:
          name: Set vcpkg path
          command: |
            export VCPKG_ROOT=$PWD/vcpkg
            export LIBRARY_PATH=$LIBRARY_PATH:$VCPKG_ROOT/installed/x64-linux/lib
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VCPKG_ROOT/installed/x64-linux/lib
            export C_INCLUDE_PATH=$C_INCLUDE_PATH:$VCPKG_ROOT/installed/x64-linux/include
            export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$VCPKG_ROOT/installed/x64-linux/include

      - run: echo | g++ -v -x c++ -E -
      - run: ls -l $VCPKG_ROOT/installed/x64-linux/include/boost
      - run: mkdir -p build && cd build
      - run: g++ -shared -o libDll_foo.so -O2 ./Dll_foo/Tictoc.cpp -std=c++20
      - run: g++ -O2 -I ./Dll_foo ./Delegate/TestDelegate.cpp -o TestDelegate -Wl,-L"./" -Wl,-rpath="./" -std=c++20 -lDll_foo -lboost_filesystem
      - run: ./TestDelegate

  build_macos:
    macos:
        xcode: 14.2.0
    steps:
      - checkout
      - run: xcodebuild -version

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  workflow1:
    jobs:
      - build_ubuntu_manually
