name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  msvc2022:
    # windows-latest means Windows 10. And automatically installs Visual Studio 2019
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/setup-windows-10-sdk-action
    # - name: Setup Windows 10 SDK
    #   uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
    #   with:
    #     sdk-version: 18362

    # Also see: https://github.com/microsoft/setup-msbuild/issues/77
    - name: Setup msbuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.10.5
 
    # https://github.com/marketplace/actions/build-boost
    - name: Install boost
      uses: egor-tensin/build-boost@v1
      id: install-boost
      with:
        version: 1.85.0
        libraries: filesystem
        configuration: Debug
        platform: x64
        static: 1
        static-runtime: 1
        toolset: msvc143

    # https://github.com/marketplace/actions/print-folder-tree
    - name: Print boost directory
      uses: jaywcjlove/github-action-folder-tree@main
      with:
        path: ${{ steps.install-boost.outputs.librarydir }}
        depth: 1

    - name: Build solution
      run: msbuild -t:rebuild /p:Configuration=Debug /p:Platform=x64 TestDelegate.sln
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.root }}
        BOOST_LIB: ${{ steps.install-boost.outputs.librarydir }}

    #- name: Run tests
    
