name: Windows CI

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'README.md'
        - '.gitignore'
        - 'CMakeLists.txt'
        - 'Delegate/CMakeLists.txt'
        - 'Dll_foo/CMakeLists.txt'
        - 'Scripts/**'
        - '.circleci/**'
        - 'appveyor.yml'
        - 'Linux_old/**'
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  msvc2022:
    # windows-latest means Windows 10. And automatically installs Visual Studio 2019
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    # Also see: https://github.com/marketplace/actions/setup-msbuild
    - name: Setup msbuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.10.6

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install boost-filesystem:x64-windows-static
        .\vcpkg\vcpkg integrate install

    - name: Build solution
      run: msbuild -t:rebuild /p:Configuration=Debug /p:Platform=x64 TestDelegate.sln

    - name: Run tests
      shell: cmd
      run: .\x64\Debug\Delegate.exe
    
